### ISSUE TITLE
Setup ability to propogate label list across entire orgs

### ISSUE THREAD

**Issue by lannonbr** [lannonbr/issue-label-manager-action#1]
For GitHub orgs that share a list of labels across all of the repos in their org, I could enhance this to store the JSON file in one repo and then propagate changes out across all of the repos.

As well, maybe in the JSON you can declare what repos in the org you want it to deploy to.

**Comment by crazy-max** [comment]
You could also use a [org-wide `.github` repo](https://github.blog/changelog/2019-02-21-organization-wide-community-health-files/).

**Comment by cvburgess** [comment]
@crazy-max have you gotten that to work? Would you mind sharing that config? I'm using .github for issue templates but have not yet used it for actions.

**Comment by crazy-max** [comment]
Hey @cvburgess, I plan to use it for actions on @portapps through [portapps/.github](https://github.com/portapps/.github). Keep you in touch!
