### ISSUE TITLE
Label prefix that action doesn't touch

### ISSUE THREAD

**Issue by janpio** [lannonbr/issue-label-manager-action#12]
This action is super promising, but this is giving me headaches:

> ... and will delete any other labels.

We tend to have a prefix for labels like `topic/*` that is dynamically used by contributors to group and collect related issues. The labels are created ad hoc, and are regularly removed when no labels are connected any more.

It would be awesome if the action could handle such a "wildcard" label and would _not_ delete such labels. (It could, if set in the configuration, update the color though to fix manual mistaked that were made when creating the labels).

**Comment by oalders** [comment]
Something like this or even a utility that allows you easily to merge existing labels with your default set of labels before running this for the first time.  The one thing that prevents me from just using this all over the place is that I don't want to clobber any existing labels on my existing repositories.

**Comment by janpio** [comment]
Yes, an alternative to my first suggestion would be a "do not delete anything" mode. With that active it would be pretty painless to try out this action.

**Comment by crazy-max** [comment]
@janpio I've used a [dry_run and skip_delete input](https://github.com/crazy-max/ghaction-github-labeler#-customizing) to avoid this behavior but a wildcard would be useful.

**Comment by lannonbr** [comment]
I added a `delete` input in 3.0.0 of this action which if set to true will delete any labels not found in the JSON file. This is set to false by default. This resolved the "don't delete anything mode" portion of this issue so I'm going to close the issue.

**Comment by janpio** [comment]
I love getting these messages on issues from a few years ago 👍 Thanks @lannonbr, keep up the great work.
