### ISSUE TITLE
Label descriptions are not affected

### ISSUE THREAD

**Issue by kolappannathan** [lannonbr/issue-label-manager-action#13]
I was trying this action in my [repo](https://github.com/kolappannathan/dotnet-core-web-api-boilerplate), the label descriptions were neither created nor updated. Here is the action logs when it

 1. Created the labels - [log](https://github.com/kolappannathan/dotnet-core-web-api-boilerplate/commit/f419e26616030ea2a5a00e8e41c1140fa8d45798/checks?check_suite_id=270912128).
 2. It ran in the next commit updating label but no change is done - [log](https://github.com/kolappannathan/dotnet-core-web-api-boilerplate/commit/cd8fde45bbb922269d29778ab59f16d893fc6f54/checks?check_suite_id=270914844).

**Comment by Maikel-Koek** [comment]
Same here! Using `lannonbr/issue-label-manager-action@2.0.0`

**Comment by lannonbr** [comment]
Should be resolved now as of 3.0.0 as I no longer send an update request if there isn't a description field for a label
