### ISSUE TITLE
Bug: You have triggered an abuse detection mechanism. 

### ISSUE THREAD

**Issue by TGTGamer** [lannonbr/issue-label-manager-action#14]
Heya guys, we have hit an issue because our config has 100+ labels which we use across multiple repos. To ensure they are sync'ed up we used your application until recently, where we have this issue: 

`(node:2624) UnhandledPromiseRejectionWarning: HttpError: You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.
    at /home/runner/work/_actions/lannonbr/issue-label-manager-action/2.0.0/lib/index.js:86:941
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`

We believe that the simple solution would be to check if the label is already built, then skip it. This would allow us to run the command a couple of times to generate the entire set.

**Comment by lannonbr** [comment]
This I believe should possibly be resolved as it no longer sends an `update` if the description field of a label is not defined. This likely was your issue so I'm closing the issue
