### ISSUE TITLE
Update action version in README to prevent loss of labels

### ISSUE THREAD

**Issue by rolfkleef** [lannonbr/issue-label-manager-action#18]
I just added a PR to update the Action version in the README https://github.com/lannonbr/issue-label-manager-action/pull/17

When copying the example code, the `delete` option says it defaults to `false`, but when either setting it explicitly to false or removing the setting (trusting the default) will result in version 2 deleting labels.

    Warning: Unexpected input(s) 'delete', valid inputs are ['']
    Run lannonbr/issue-label-manager-action@2.0.0
    [Action] Deleting Label: test

**Comment by lannonbr** [comment]
Merged #17 so closing this issue
