### ISSUE TITLE
"Validation Failed" for each request, description missing on new label

### ISSUE THREAD

**Issue by citycide** [lannonbr/issue-label-manager-action#9]
I set this up here: [citycide/trilogy/.github/workflows/update-issue-labels.yml](https://github.com/citycide/trilogy/blob/master/.github/workflows/update-issue-labels.yml)

On the original run, all the existing labels remained as they were. A newly added one (called `zzz: testing`) for testing purposes was created but the description field is empty.

It seems the request sent for every label fails with the following message:

`HttpError: Validation Failed`

Full log here: https://github.com/citycide/trilogy/runs/204987665#step:3:30

**Comment by lannonbr** [comment]
This should be resolved as of 3.0.0 as now it won't try updating if there isn't a description.
